In [34]:
import pandas as pd
import numpy as np
from numpy.linalg import inv

In [2]:
pd.__version__

'2.2.3'

In [3]:
df = pd.read_csv('laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [4]:
records = df.shape
records

(2160, 12)

In [47]:
len(list(df['Brand'].unique()))

27

In [5]:
bool_df = df.notna()
df1 = bool_df[bool_df != False]

In [6]:
df1 = df1.dropna(axis=1)

In [7]:
df1

Laptop  Status  Brand  Model   CPU   RAM  Storage  Touch  Final Price
0       True    True   True   True  True  True     True   True         True
1       True    True   True   True  True  True     True   True         True
2       True    True   True   True  True  True     True   True         True
3       True    True   True   True  True  True     True   True         True
4       True    True   True   True  True  True     True   True         True
...      ...     ...    ...    ...   ...   ...      ...    ...          ...
2155    True    True   True   True  True  True     True   True         True
2156    True    True   True   True  True  True     True   True         True
2157    True    True   True   True  True  True     True   True         True
2158    True    True   True   True  True  True     True   True         True
2159    True    True   True   True  True  True     True   True         True

[2160 rows x 9 columns]

In [8]:
print(f'number of columns with NaN values : {df.shape[1] - df1.shape[1]}')

number of columns with NaN values : 3


In [9]:
df_filter = df[
    df['Brand'] == 'Dell'
]

In [10]:
df_filter.max(numeric_only=True)

RAM              32.0
Storage        1000.0
Screen           17.0
Final Price    3936.0
dtype: float64

In [14]:
median = df['Screen'].median()
median

np.float64(15.6)

In [15]:
mode = df['Screen'].mode()
mode

0    15.6
Name: Screen, dtype: float64

In [17]:
fill_screen = df['Screen'].fillna(mode)

In [19]:
median1 = fill_screen.median()
median1

np.float64(15.6)

In [23]:
df_injoo = df[
    df['Brand'] == 'Innjoo'
]

df_injoo = df_injoo[['RAM','Storage', 'Screen']]
X = df_injoo.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [26]:
XTX = X.T
XTX

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [36]:
mul = np.matmul(X,XTX)
mul

array([[ 65843.36, 131379.36,  16635.96,  16651.96,  33035.96,  33035.96],
       [131379.36, 262451.36,  33019.96,  33035.96,  65803.96,  65803.96],
       [ 16635.96,  33019.96,   4310.81,   4318.81,   8414.81,   8414.81],
       [ 16651.96,  33035.96,   4318.81,   4330.81,   8426.81,   8426.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81]])

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [39]:
inverse = np.linalg.inv(XTX)

LinAlgError: Last 2 dimensions of the array must be square